server:
  port: 8087

active: test


#服务名字
spring:
  application:
    name: config
  profiles:
    active: native


  # 配置中心
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/${active}/


eureka:
#客户端
  client:
#注册中心地址
    service-url:
      defaultZone: http://localhost:8000/eureka/